env: flex       # Flex environment
runtime: java   # Java runtime
runtime_config:
  jdk: openjdk8 # use OpenJDK 8

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 4
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.7
